FROM node:15

RUN apt-get update && apt-get install -y wget
ENV DOCKERIZE_VERSION v0.6.1
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

RUN mkdir /usr/src/app/
COPY ./package.json /usr/src/app/
RUN mkdir /data
RUN ln -s /usr/src/app/package.json /data/.

WORKDIR /data

RUN npm install --no-optional && npm cache clean --force

ENV NODE_PATH /data/node_modules/

WORKDIR /usr/src/app/

EXPOSE 3000